# Generated by Django 6.0.7 on 2026-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_cartitem_delivery_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
