# Generated by Django 6.0.7 on 2026-09-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_delivery_options_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
