"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-rxg4km%cz^##-25h#1i3x=+g4--+ri2&7-z@)-1zswe$8kw#=!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

raw_allowed_hosts = config('ALLOWED_HOSTS', default='*,eacyclic.com,www.eacyclic.com,.onrender.com')
ALLOWED_HOSTS = [h.strip() for h in raw_allowed_hosts.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

_DATABASE_URL = config('DATABASE_URL', default='').strip()
if 'channel_binding' in _DATABASE_URL:
    _DATABASE_URL = _DATABASE_URL.replace('&channel_binding=require', '').replace('?channel_binding=require', '')
if not _DATABASE_URL:
    _DATABASE_URL = f'sqlite:///{BASE_DIR / "db.sqlite3"}'

use_sqlite = False
if _DATABASE_URL.startswith('postgres'):
    try:
        import importlib
        importlib.import_module('django.db.backends.postgresql.base')
        parsed_db = dj_database_url.parse(
            _DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        )
        DATABASES = {'default': parsed_db}
    except Exception as err:
        print(f"[DATABASE WARNING] PostgreSQL connection failed ({err}). Falling back to local SQLite.")
        use_sqlite = True
else:
    use_sqlite = True

if use_sqlite:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'


# Email Configuration
# Render free tier BLOCKS outbound SMTP (port 587/465) — OSError: [Errno 101] Network is unreachable
# Solution: Use Resend HTTP API (free 3000 emails/month, no SMTP needed)
# Sign up at https://resend.com — get an API key — add it to Render env vars.
#
# Priority:
#   1. RESEND_API_KEY set  → use Resend HTTP API (works on Render free tier)
#   2. EMAIL creds set     → use SMTP (works locally, NOT on Render free tier)
#   3. Neither set         → Console backend (prints to terminal/logs)

RESEND_API_KEY = config('RESEND_API_KEY', default='').strip()
RESEND_FROM_EMAIL = config('RESEND_FROM_EMAIL', default='Eacyclic <noreply@eacyclic.com>').strip()

_email_user = config('EMAIL_HOST_USER', default='').strip()
_email_pass = config('EMAIL_HOST_PASSWORD', default='').strip()

if _email_user and _email_pass and not _email_user.startswith('your_'):
    EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
    EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
    EMAIL_HOST_USER = _email_user
    EMAIL_HOST_PASSWORD = _email_pass
    EMAIL_TIMEOUT = 30
    DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=_email_user)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@eacyclic.com'



CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=True, cast=bool)

raw_cors_origins = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173,http://127.0.0.1:3000,https://eacyclic.com,https://www.eacyclic.com'
)
CORS_ALLOWED_ORIGINS = [o.strip().rstrip('/') for o in raw_cors_origins.split(',') if o.strip()]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.eacyclic\.com$",
    r"^https://eacyclic\.com$",
    r"^https://.*\.onrender\.com$",
]

CORS_ALLOW_CREDENTIALS = True

raw_csrf_origins = config(
    'CSRF_TRUSTED_ORIGINS',
    default='https://*.onrender.com,http://localhost:8000,http://127.0.0.1:8000,http://localhost:5173,https://eacyclic.com,https://www.eacyclic.com'
)
CSRF_TRUSTED_ORIGINS = [o.strip().rstrip('/') for o in raw_csrf_origins.split(',') if o.strip()]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'EXCEPTION_HANDLER': 'api.views.custom_exception_handler',
}
